# Generated by Django 3.2.5 on 2021-07-23 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigslistjunior', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Category',
        ),
    ]
