# Generated by Django 3.2.5 on 2021-07-23 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigslistjunior', '0002_rename_listing_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='category_id',
        ),
    ]
