# Generated by Django 3.2.5 on 2021-07-23 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craigslistjunior', '0003_rename_category_post_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craigslistjunior.category'),
        ),
    ]
