# Generated by Django 3.2.5 on 2021-07-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslistjunior', '0004_alter_post_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
