# Generated by Django 3.2.5 on 2021-07-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210722_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_by',
            field=models.CharField(default='Mr. Orange', max_length=100),
            preserve_default=False,
        ),
    ]
