# Generated by Django 3.2.5 on 2021-07-23 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_post_posted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desctiption',
            new_name='description',
        ),
    ]
